services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports: 
      - "${MYSQL_DB_PORT}:${MYSQL_DB_PORT}"
    volumes: 
      - db-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7.0
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  db-data:
  redis-data:

networks:
  app-network:
    driver: bridge