services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports: 
      - "${MYSQL_DB_PORT}:${MYSQL_DB_PORT}"
    volumes: 
      - db-data:/var/lib/mysql

volumes:
  db-data:
